### ISSUE TITLE
Android Basics: Lunch Tray app

### ISSUE THREAD

**Issue by harr1424** [google-developer-training/android-basics-kotlin-lunch-tray-app#17] opened 2022-02-13 01:00 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-project-lunch-tray?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-lunch-tray

**In which task and step of the codelab can this issue be found?**
Test Your App

**Describe the problem**
When attempting to run the app a NullPointerException results in app crashing: 
```
Caused by: java.lang.NullPointerException: null cannot be cast to non-null type androidx.navigation.fragment.NavHostFragment
        at com.example.lunchtray.MainActivity.onCreate(MainActivity.kt:32)
```

**Steps to reproduce?**
1. Implement MainActivity.kt to match the MainActivity.kt implementation in the prior Cupcake codelab and documentation that describes initializing a navHostFragment: 
```
class MainActivity : AppCompatActivity() {

    private lateinit var navController: NavController

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val navHostFragment = supportFragmentManager // NULL CANNOT BE CAST TO NON NULL TYPE 
            .findFragmentById(R.id.nav_host_fragment) as NavHostFragment
        navController = navHostFragment.navController

        setupActionBarWithNavController(navController)
    }

    override fun onSupportNavigateUp(): Boolean {
        return navController.navigateUp() || super.onSupportNavigateUp()
    }
}
```
2.  Attempt to run app, it will crash and output the following error in Logcat: 
```
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.lunchtray/com.example.lunchtray.MainActivity}: java.lang.NullPointerException: null cannot be cast to non-null type androidx.navigation.fragment.NavHostFragment
```
**Versions**
_Android Studio version:_  2021.1.1 Patch 1
_API version of the emulator:_  30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/84741727/153733818-3712b814-6949-4e2d-a29f-9849a315d7cd.png)
![image](https://user-images.githubusercontent.com/84741727/153733826-07b5f9a6-bd5c-4f85-bf93-be80ba50ed03.png)

**Comment by ghs-gs** [comment] 2022-02-13 17:47
Hi, can you please try it with adding the code below?

```
......
class MainActivity : AppCompatActivity() {
    private lateinit var binding: ActivityMainBinding
........

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)

...............
```

**Comment by harr1424** [comment] 2022-02-13 22:15
The code you provided fixed the issue, and it is now clear to me why it is necessary to set content view.  

I based my approach to this project off of the previous Cupcake Codelab, and curiously in that Codelab, the content view was never set: 
```
/**
 * Activity for cupcake order flow.
 */
class MainActivity : AppCompatActivity(R.layout.activity_main) {

    private lateinit var navController: NavController

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val navHostFragment = supportFragmentManager
            .findFragmentById(R.id.nav_host_fragment) as NavHostFragment
        navController = navHostFragment.navController

        setupActionBarWithNavController(navController)
    }

    override fun onSupportNavigateUp(): Boolean {
        return navController.navigateUp() || super.onSupportNavigateUp()
    }

}
```

**Comment by gouravkhunger** [comment] 2022-03-12 09:49
Hey @harr1424, in the cupcake app, we pass in the layout file `R.layout.activity_main` to the constructor of `AppCompatActivity()` here:

```
class MainActivity : AppCompatActivity(R.layout.activity_main) { ... }
```

`AppCompatActivity` inherits from `FragmentActivity`, which in turn inherits from `ComponentActivity` (you can know this by pressing Control/Command clicking on the class name).

Inside `ComponentActivity`, if we pass in the layout file to the constructor, it handles setting up content view for us:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/46792249/158013042-25bff64e-7c61-45d3-a2b7-c885c7ff914b.png">

That's the reason we don't need `setContentView()` there but we need it in your case. If you pass the layout into the constructor, you can skip `setContentView()`.

Hope this helps :)

**Comment by osuleymanova** [comment] 2022-05-20 21:28
The issue is closed as resolved.

**Closed by osuleymanova** 2022-05-20 21:28 UTC
