### ISSUE TITLE
Android Basics: Lunch Tray app

### ISSUE THREAD

**Issue by kthib16** [google-developer-training/android-basics-kotlin-lunch-tray-app#19] opened 2022-03-01 21:07 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-project-lunch-tray?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-lunch-tray#3

**In which task and step of the codelab can this issue be found?**
NavigationTests ( https://github.com/google-developer-training/android-basics-kotlin-lunch-tray-app/blob/main/app/src/androidTest/java/com/example/lunchtray/NavigationTests.kt )

**Describe the problem**
In testing the app navigation, the tests use the wrong id for the start Fragment (R.id.startOrder instead of R.id.startOrderFragment)

**Steps to reproduce?**
1. Go to... https://github.com/google-developer-training/android-basics-kotlin-lunch-tray-app/blob/main/app/src/androidTest/java/com/example/lunchtray/NavigationTests.kt 
2. Click on...run tests
3. See error...startOrder not found

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2022-05-20 22:45
Duplicate of #7, #12, #14

**Closed** 2024-01-11 21:22 UTC
