### ISSUE TITLE
Android Basics: Lunch Tray app

### ISSUE THREAD

**Issue by rodolphebossin** [google-developer-training/android-basics-kotlin-lunch-tray-app#12] opened 2022-01-03 18:25 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-project-lunch-tray?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-lunch-tray#3

**In which task and step of the codelab can this issue be found?**
In the NavigationTests class

**Describe the problem**
I think there is an error on the id of the startOrderFragment : R.id.startOrder instead of R.id.startOrderFragment

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
<img width="766" alt="Capture d’écran 2022-01-03 à 19 24 50" src="https://user-images.githubusercontent.com/72972910/147965790-e30dc356-9846-4d10-837b-b89d9999ef0c.png">

**Comment by osuleymanova** [comment] 2022-05-20 22:41
Duplicate of #7

**Closed** 2024-01-11 21:22 UTC
