### ISSUE TITLE
Android Basics: Lunch Tray app

### ISSUE THREAD

**Issue by eliasroebl** [google-developer-training/android-basics-kotlin-lunch-tray-app#14] opened 2022-01-24 06:47 UTC
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-project-lunch-tra

**In which task and step of the codelab can this issue be found?**

4. Test your app!

**Describe the problem**

When I started testing, the error: "Unresolved reference: startOrder" occurred
The error pops up throughout NavigationTests.
When I refactored "R.id.startOrder" to "R.id.startOrderFragment" everything worked perfectly.

Errors occur in **com.example.lunchtray.NavigationTests** on lines: 83, 126, 163, 200, 218

**Steps to reproduce?**
Just clone the project, build it and run the tests.
There is no id "startOrder", so it should fail

![image](https://user-images.githubusercontent.com/31956958/150734947-33c2e660-be54-4b2f-a942-daed14619b07.png)

**Comment by harr1424** [comment] 2022-02-12 17:36
This helped me out, thank you for posting!

**Comment by osuleymanova** [comment] 2022-05-20 22:42
Duplicate of #7 , #12

**Closed** 2024-01-11 21:22 UTC
